--- QUESTION 1 ----
CREATE TABLE VILLE (
  VILLE VARCHAR2(50) NOT NULL,
  X_MIN INT,
  X_MAX INT,
  Y_MIN INT, 
  Y_MAX INT,
  PRIMARY KEY(VILLE))
  
CREATE TABLE AGENCE (
  CODE VARCHAR2(50) NOT NULL,
  VILLE VARCHAR2(50) NOT NULL,
  PRIMARY KEY(VILLE),
  FOREIGN KEY(VILLE) REFERENCES VILLE(VILLE))
  
CREATE TABLE AVION (
  AVNUM VARCHAR2(50) NOT NULL,
  AVNOM VARCHAR2(50) NOT NULL,
  LOCALISATION VARCHAR2(50) NOT NULL,
  CAPACITE INT,
  PRIMARY KEY(AVNUM),
  FOREIGN KEY(LOCALISATION) REFERENCES VILLE(VILLE))
  
CREATE TABLE PILOTE (
  PLNUM VARCHAR2(50) NOT NULL,
  PLNOM VARCHAR2(50) NOT NULL,
  PLPRENOM VARCHAR2(50) NOT NULL,
  VILLE VARCHAR2(50),
  SALAIRE INT,
  PRIMARY KEY(PLNUM),
  FOREIGN KEY(VILLE) REFERENCES VILLE(VILLE))

CREATE TABLE VOL2 (
  VOLNUM VARCHAR2(50) NOT NULL,
  PLNUM VARCHAR2(50) NOT NULL,
  AVNUM VARCHAR2(50) NOT NULL,
  VILLEDEP VARCHAR2(50),
  VILLEARR VARCHAR2(50),
  HEUREDEP VARCHAR2(50),
  HEUREARR VARCHAR2(50),
  PRIMARY KEY(VOLNUM),
  FOREIGN KEY(AVNUM) REFERENCES AVION(AVNUM),
  FOREIGN KEY(PLNUM) REFERENCES PILOTE(PLNUM),
  FOREIGN KEY(VILLEDEP) REFERENCES VILLE(VILLE),
  FOREIGN KEY(VILLEARR) REFERENCES VILLE(VILLE))
  
  ---QUESTION 2---
  
  ---table VILLE---
  INSERT INTO VILLE VALUES ('Dijon', 8950,9180,4840,5050);
  INSERT INTO VILLE VALUES ('Lyon', 8820,9080,7020,7230);
  INSERT INTO VILLE VALUES ('Paris', 6310,6560,2940,3110);
  INSERT INTO VILLE VALUES ('Toulouse', 6310,6560,2940,3110);
  ---table AVION---
  INSERT INTO AVION VALUES ('2', 'A310','Dijon',300);
  INSERT INTO AVION VALUES ('1','A300', 'Lyon', 300);
  INSERT INTO AVION VALUES ('3','B707','Paris', 250);
  ---table AGENCE---
  INSERT INTO AGENCE VALUES('AG001', 'Paris');
  INSERT INTO AGENCE VALUES ('AG004', 'Lyon');
  ---table PILOTE---
  INSERT INTO PILOTE VALUES('1', 'Solomon', 'Asres','Paris', 21000);
  INSERT INTO PILOTE VALUES('4', 'Dupont', 'Nicolas', 'Paris', 17000);
  ---table VOL2---
  INSERT INTO VOL2 VALUES('2','1','2','Paris','Toulouse',17,18);


---QUESTION 3---
RENAME VOL2 TO TRAJET;
RENAME PILOTE TO PERSONNEL;

---QUESTION 4---
UPDATE TRAJET SET VILLEDEP = 'Lille', HEUREARR = 17 WHERE VOLNUM = 4;

---QUESTION 5---
DELETE FROM TRAJET WHERE VOLNUM = 5;

---QUESTION 6---
ALTER TABLE PERSONNEL
ADD FONCTION VARCHAR2(50) DEFAULT 'Pilote';

---PARTIE II---

---QUESTION 1---
DESCRIBE TRAJET;

---QUESTION 2---
SELECT VILLEDEP, VILLEARR FROM TRAJET;

---QUESTION 3---
SELECT PLNOM AS Nom, PLPRENOM AS Prenom, VILLE AS Ville
FROM PERSONNEL ORDER BY Nom, Prenom;

---QUESTION 4---
SELECT PLNOM, PLPRENOM, SALAIRE
FROM PERSONNEL
WHERE SALAIRE >20000;

---QUESTION 5---
--option 1--
SELECT PLNOM,PLPRENOM FROM PERSONNEL
WHERE SALAIRE = 10000 OR SALAIRE = 20000;

--option 2--
SELECT PLNOM,PLPRENOM FROM PERSONNEL
WHERE SALAIRE IN (SELECT SALAIRE FROM PERSONNEL 
                  WHERE SALAIRE = 10000 OR SALAIRE = 20000);
--option 3--
SELECT PLNOM,PLPRENOM FROM PERSONNEL
WHERE SALAIRE = ANY (SELECT SALAIRE FROM PERSONNEL 
                  WHERE SALAIRE = 10000 OR SALAIRE = 20000);
                  
---QUESTION 6---
SELECT PLNOM, PLPRENOM FROM PERSONNEL
WHERE AVG(SALAIRE) < (SELECT SALAIRE FROM PERSONNEL);