--TD4---
/*Création de la Table EMP2*/
CREATE TABLE EMP2 (
  NUMEMP INT NOT NULL,
  NOM_COMPLET VARCHAR2(50) NOT NULL,
  SALAIRE INT,
  VILLE VARCHAR(50) NOT NULL,
  CP INT NOT NULL,
  TEL VARCHAR2(10),
  FAX VARCHAR(20),
  PRIMARY KEY(NUMEMP))

DROP TABLE EMP2;
/*INSERTION DANS LA TABLE*/

INSERT INTO EMP2 VALUES (1,'DUPUIS Yvonne',NULL, 'Lyon', 69000, '0472546585',NULL);
INSERT INTO EMP2 VALUES (2,'DUPOND Jean',NULL, 'Paris', 75000, NULL,NULL);
INSERT INTO EMP2 VALUES (3,'CRINIERE Belle',NULL, 'Grenoble', 38001, NULL,NULL);
INSERT INTO EMP2 VALUES (4,'AUBERT Louis',NULL, 'Lyon', 69100, '0478556585',NULL);
INSERT INTO EMP2 VALUES (5,'MAURI John',NULL, 'Anglet', 64200, NULL,NULL);

/*MAJ DES TABLES*/
UPDATE EMP2 SET NOM_COMPLET = 'XAVIER Richard', SALAIRE = 30000, VILLE = 'Anglet', CP = 64200 WHERE NUMEMP = 2;
UPDATE EMP2 SET NOM_COMPLET = 'NICOLLE Chris', SALAIRE = 20000, VILLE = 'Anglet', CP = 64200, TEL = '06809889' WHERE NUMEMP = 3;

/*QUESTION 4*/
UPDATE EMP SET SALAIRE = &nouveau_salaire
WHERE NUMEMP = &numero_employe;

/*QUESTION 6*/
SELECT NOM_COMPLET, VILLE FROM EMP2;

/*QUESTION 7*/
SELECT DISTINCT COUNT(VILLE) FROM EMP2;

/*QUESTION 8*/
SELECT NOM_COMPLET FROM EMP2
WHERE VILLE = 'Anglet';

/*QUESTION 9*/
SELECT NOM_COMPLET FROM EMP2
WHERE Tel IS NOT NULL;

/*QUESTION 10*/
UPDATE EMP2 SET TEL = '0606060606', FAX='abcdef@gmail.com'
WHERE NOM_COMPLET LIKE 'XAVIER%';

/*PARTIE 2*/

set serveroutput on

/*QUESTION 11*/
CREATE OR REPLACE PROCEDURE INSERT_EMP
(NumEMP NUMBER, Nom VARCHAR2, Sal NUMBER, Ville VARCHAR2, Cp INT, Tel VARCHAR2, Fax VARCHAR2) AS
NomPersonne EMP2.NOM_COMPLET%TYPE;
BEGIN 
    INSERT INTO EMP2 VALUES(NumEMP, Nom, Sal, Ville, Cp, Tel, Fax);
    COMMIT; 
    dbms_output.put_line('Insertion validée');
END;

BEGIN 
  INSERT_EMP(7,'PICOULET-SONDER Alexandre', 30000, 'Bayonne', 64100, NULL, NULL);
END;

/*QUESTION 12*/
CREATE OR REPLACE PROCEDURE MAJ_EMP(NomEMP EMP2.NOM_COMPLET%TYPE,SalaireEMP INT) AS
BEGIN
    UPDATE EMP2 SET SALAIRE = SalaireEMP
    WHERE EMP2.NOM_COMPLET = NomEMP;
    dbms_output.put_line('Opération Réussie !');
END;

BEGIN 
  MAJ_EMP('XAVIER Richard', 25000);
END;

/*QUESTION 13*/
CREATE OR REPLACE FUNCTION COUNT_EMP
RETURN INT IS
valeur_renvoye INT;
BEGIN 
  SELECT COUNT(EMP2.NUMEMP)
  INTO valeur_renvoye
  FROM EMP2;
  
  RETURN valeur_renvoye;
END;

BEGIN 
  DBMS_OUTPUT.PUT_LINE('Il y a exactement ' || COUNT_EMP || ' employés');
END;

/*QUESTION 14*/
CREATE OR REPLACE FUNCTION COUNT_EMP(uneVille VARCHAR2)
RETURN INT IS
valeur_renvoye INT;
BEGIN 
  SELECT COUNT(EMP2.NUMEMP)
  INTO valeur_renvoye
  FROM EMP2
  WHERE EMP2.VILLE = uneVille;
  
  RETURN valeur_renvoye;
END;

BEGIN 
  DBMS_OUTPUT.PUT_LINE('Il y a exactement ' || COUNT_EMP('Anglet') || ' employés dans la ville');
END;


