/**
TD1 R4.03 qualité et non 
*/

/*Question 1 : */

CREATE OR REPLACE TYPE Coordonnee_t AS OBJECT
(Ville VARCHAR2(50) NOT NULL, 
CP NUMBER NOT NULL, 
Tel VARCHAR2(50), 
Fax VARCHAR2(50)) ;

CREATE TABLE EMP_OBJ (
NUM_EMP NUMBER NOT NULL, 
NOM_COMPLET VARCHAR2(50) NOT NULL,
SALAIRE VARCHAR2(50),
COORDONNEES Coordonnee_t,
PRIMARY KEY (NUM_EMP)) ;

/*Question 2 :*/

INSERT INTO EMP_OBJ VALUES (14, "XAVIER Richard", NULL, Coordonnee_t("Lyon", 69000, NULL, NULL)) ;
INSERT INTO EMP_OBJ VALUES (15, "NICOLLE Chris", NULL, Coordonnee_t("Paris", 75000, NULL, NULL)) ;

/*Question 3 :*/

UPDATE EMP_OBJ SET COORDONNEES.Ville = "Anglet", SALAIRE = 30000, COORDONNEES.CP = 64600 WHERE NUM_EMP = 14 ;
UPDATE EMP_OBJ SET COORDONNEES.Ville = "Anglet", SALAIRE = 20000, COORDONNEES.Tel = "06989898" WHERE NUM_EMP = 15 ;

/*Question 3.2 :*/

SELECT * FROM EMP_OBJ ;

/*Question 4 :*/

CREATE OR REPLACE PROCEDURE updateEmp_OBJ_AvecEMP AS
CURSOR c_emp IS SELECT * FROM EMP ;
BEGIN
    FOR ligne IN c_emp LOOP
        INSERT INTO EMP_OBJ VALUES (ligne.NUM_EMP, ligne.NOM_COMPLET, ligne.SALAIRE, Coordonnee_t(ligne.Ville, ligne.CP, ligne.Tel, ligne.Fax) ;
    END LOOP ;
    COMMIT;
END ;


/*Question 5 :*/

SELECT DISTINCT COORDONNEES.Ville 
FROM EMP_OBJ ;

/*Question 6 :*/

SELECT COORDONNEES.NOM_COMPLET 
FROM EMP_OBJ 
WHERE COORDONNEES.Tel = NULL ;

/*Question 7 :*/

UPDATE EMP_OBJ SET COORDONNEES.Tel = "06989898", COORDONNEES.Fax = "0101010101" WHERE NOM_COMPLET = "XAVIER Richard" ;

/*Question 8 :*/

UPDATE EMP_OBJ SET e.coordonnee = Coordonnee_t(NULL,NULL,NULL)
WHERE e.NOM_COMPLET = "NICOLLE Chris" ;